from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch  # Import inch for units


def create_cover_page_with_background(pdf_filename, year):
    # Create a canvas object with A4 size
    c = canvas.Canvas(pdf_filename, pagesize=A4)
    
    # Define the page width and height
    width, height = A4

    # Add NBA logo at the center (adjust position and size as needed)
    logo_size = 11.7 * inch  # Increase logo size
    logo_path = "nba_logo.png"
    c.drawImage(logo_path, (width - logo_size) / 2, height - 11.7*inch, logo_size, logo_size, preserveAspectRatio=True)

    
    # Set the title text
    title = f"NBA Team Statistics {year}"
    
    # Set font and size for the title
    c.setFont("Helvetica-Bold", 28)
    c.setFillColor(colors.black)  # Black text to stand out on the colorful background
    
    # Add the title at the center
    c.drawCentredString(width / 2, height - 3.5 * inch, title)
    
    # Optionally, add a subtitle or author information
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 11.0 * inch, "Generated by Enes Cevik")
    
    # Finalize the page
    c.showPage()
    c.save()

# Example usage
pdf_filename = "nba_team_statistics_2024_background_only.pdf"
year = 2024

create_cover_page_with_background(pdf_filename, year)
