from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch  # Import inch for units
from NBA_report.scrape_nba import *
import cairosvg
import pandas as pd

def download_and_convert_svg_to_png(svg_url, output_filename):
    # Download the SVG image
    response = requests.get(svg_url)
    if response.status_code == 200:
        # Convert the SVG data to PNG and save it
        cairosvg.svg2png(bytestring=response.content, write_to=output_filename)
        print(f"SVG image saved as PNG: {output_filename}")
    else:
        print(f"Failed to download the image. Status code: {response.status_code}")

def create_report(pdf_filename):
    # Create a canvas object with A4 size
    c = canvas.Canvas(pdf_filename, pagesize=A4)
    
    # Define the page width and height
    width, height = A4

    svg_url = "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg"
    png_filename = "team_logo.png"

    # Download and convert the SVG to PNG
    download_and_convert_svg_to_png(svg_url, png_filename)

    # Add NBA logo at the center (adjust position and size as needed)
    logo_size = 3 * inch  # Increase logo size
    logo_path = "team_logo.png"
    c.drawImage(logo_path, (width - logo_size) / 2, height - 11.7*inch, logo_size, logo_size, preserveAspectRatio=True)
    
    # Set font and size for the title
    c.setFont("Helvetica-Bold", 28)
    c.setFillColor(colors.black)  # Black text to stand out on the colorful background
    
    # Add the title at the center
    c.drawCentredString(width / 2, height - 3.5 * inch, title)
    
    # Optionally, add a subtitle or author information
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 11.0 * inch, "Generated by Enes Cevik")
    
    # Finalize the page
    c.showPage()
    c.save()
 
# Example usage
pdf_filename = "nba_team_statistics_background_only.pdf"
year = 2024

create_cover_page_with_background(pdf_filename, year)
